### ISSUE TITLE
get_discussions_by x

### ISSUE THREAD

**Issue by cbanwell** [VIM-Arcange/Steem.NET#3]
The get_discussions_by_trending,hot etc are left out of the csteemd.cs class, is there a specific reason these weren't integrated?

**Comment by VIM-Arcange** [comment]
No reason except me being lazy and not using those APIs.
Feel free to Implement them and make a PR if you want.

**Comment by cbanwell** [comment]
Yeah I tried to implement get_discussions_by_trending
with 
public JArray get_discussions_by_trending(string tag, uint limit)
        {
            ArrayList arrParams = new ArrayList();
            arrParams.Add(tag);
            arrParams.Add(limit);

            return call_api_array(MethodBase.GetCurrentMethod().Name, arrParams);
        }

but when I call it I get the following error
InvalidCastException: Specified cast is not valid.
SteemAPI.CS.CSteemAPI.call_api_array (System.String strMethod, System.Collections.ArrayList arrParams) (at Assets/GoFind/Steem.NET-master/CSteemAPI.cs:87)
SteemAPI.CS.CSteemd.get_discussions_by_trending (System.String tag, System.UInt32 limit) (at Assets/GoFind/Steem.NET-master/CSteemd.cs:181)

any ideas? I've been scratching my head for a day now lol
